<div id="landing" class="container contain-all">
<?php 
/**
* Landing Page
* this will grab the newest 6 projects and display the for all the world to see
*/
?>

<?php if($this->user_id != "") { ?>
<a class="logout" href="/account/logout">logout</a>

<span class="user"><?= "User: " . $this->first_name . " " . $this->last_name; ?></span>
<?php 	} ?>
	

<span class="aipd"></span>
<h1>Ts Projects</h1>

<div class="entryForm">

<h2>Hello! You've reached TSProject, the Project Admin for the Art Institute's WDIM Department's Touch Screen Display.</h2>

<div class="options">
	<p>What would you like to do? </p>
	<?php if($this->user_id != "") { ?>
	<a class="view" href="/account/view">view your account</a>
	
	<a class="newProject" href="/project/new">add a new project</a>
<?php		} else { ?>

	<p class="descrip">Sign In:</p>
	<form action="/account/login" method="post">
		<label>Email</label>
		<input name="email"id="email" type="text" />
		<br />
	
		<label>Password</label>
		<input name="pass"id="pass" type="text" />
	
	    <input type="submit" value="submit" id="submit"/>
	</form>
	
	<p class="descrip">Start a new Account:</p>
	<a class="create" href="/account/new">create new account</a>
<?php 	} ?>
</div>		

<?php
		foreach ( $this->all_projects as $proj ) { ?>
	<div class="project">
		<div class="thumb">
			<img src="<?= (isset($proj['photo'])) ? "/uploads/{$proj['photo']['file_name']}" : "/images/default.jpg" ?>" />
		</div>
		<h3><a href="/project/view/id/<?= $proj['id'] ?>" ><?= $proj['title'] ?></a></h3>
		<h4><?= $proj['author'] ?></h4>
	</div>
<?php	} ?>
</div>
</div>
