<div id="landing" class="container">
<?php 
/**
* Landing Page
* this will grab the newest 6 projects and display the for all the world to see
*/
?>
<h1>Hello! You've reached TSProject, the Project Admin for the Art Institute's WDIM Department's Touch Screen Display.</h1>
<p>What would you like to do? </p>

<div class="options">
	<?php if($this->user_id != "") { ?>
	<a href="/account/view">View your Account</a>
	
	<a href="/project/new">Add A New Project</a>

	<a href="/account/logout">Logout</a>

	<span class="user"><?= "User: " . $this->first_name . " " . $this->last_name; ?></span>
<?php		} else { ?>
	<a href="/account/new">Create A New Account.</a>


	<form action="/account/login" method="post">
		<label>Email</label>
		<input name="email"id="email" type="text" />
		<br />
	
		<label>Password</label>
		<input name="pass"id="pass" type="text" />
	
	    <input type="submit" value="submit" id="submit"/>
	</form>
<?php 	} ?>
</div>		

<?php
		foreach ( $this->all_projects as $proj ) { ?>
	<div class="project">
		<div class="thumb">
			<img src="<?= (isset($proj['photo'])) ? "/uploads/{$proj['photo']['file_name']}" : "/images/default.jpg" ?>" />
		</div>
		<h3><a href="/project/view/id/<?= $proj['id'] ?>" ><?= $proj['title'] ?></a></h3>
		<h4><?= $proj['author'] ?></h4>
	</div>
<?php	} ?>
</div>