<h1>Hello! You've reached TSProject, the Project Admin for the Art Institute's WDIM Department's Touch Screen Display.</h1>
<p>What would you like to do? </p>

<a href="/account/new">Create A New Account.</a>

<?php if($this->user_id != "") { ?>

<a href="/account/logout">Logout</a>

<?php 		echo "User Id: " . $this->user_id; 
		} else { ?>

<form action="/account/login" method="post">
	<label>Email</label>
	<input name="email"id="email" type="text" />
	<br />
	
	<label>Password</label>
	<input name="pass"id="pass" type="text" />
	
    <input type="submit" value="submit" id="submit"/>
</form>
		
<?php 	} ?>