<div id="individual_project" class="container">
<?php 
/**
* Individual Project Info
*/
?>
<h1>Project: <?=stripslashes( $this->project['info']['title'] )?></h1>
<p>What would you like to do? </p>

<div class="options">
	<?php if($this->user_id != "") { ?>
	<a href="/">Go Home</a>
	
	<a href="/account/view">View your Account</a>
	
	<a href="/project/new">Add A New Project</a>

	<a href="/account/logout">Logout</a>

	<span class="user"><?= "User: " . stripslashes( $this->first_name ) . " " . stripslashes( $this->last_name ); ?></span>
	<?php		} else { ?>
	<a href="/account/new">Create A New Account.</a>


	<form action="/account/login" method="post">
		<label>Email</label>
		<input name="email"id="email" type="text" />
		<br />
	
		<label>Password</label>
		<input name="pass"id="pass" type="text" />
	
	    <input type="submit" value="submit" id="submit"/>
	</form>
<?php 	} ?>
</div>	

<div>
	<h2>Project Title: <?=stripslashes( $this->project['info']['title'] )?></h2>
	
	<?php 	if ( $this->user_id == $this->project['author']['id'] ) { ?>
	<div>Project Options: 
		<a href="/project/addphotos/id/<?= $this->project['info']['id'] ?>">Add Photos to Project</a>
		<a href="/project/edit/id/<?= $this->project['info']['id'] ?>">Edit Project</a>
		<a href="/project/remove/id/<?= $this->project['info']['id'] ?>">Delete Project</a>
	</div>
	<?php	} ?>
	
	<address>Project URL: <?=stripslashes( $this->project['info']['url'] )?></address>
	<h3>Project Author: <?=stripslashes( $this->project['author']['first_name'] ) . " " . stripslashes( $this->project['author']['last_name'] )?></h3>
	<div>Date: <?= ucwords( $this->project['info']['date_month'] ) . " " . $this->project['info']['date_day'] . ", " . $this->project['info']['date_year']?></div>
	
	<div>
		<?php foreach ( $this->project['photos'] as $photo ) { ?>
		<img src="/uploads/<?= $photo['file_name'] ?>" />
		<?php } ?>
	</div>
	
	<div>
		<h4>Tools:</h4>
		<ul>
			<?php 	foreach ( $this->project["tools"] as $tool ) { ?>
			<li><?= $tool ?></li>
			<?php	} ?>
		</ul>
	</div>
	<div>
		<h4>Languages:</h4>
		<ul>
			<?php 	foreach ( $this->project["languages"] as $language ) { ?>
			<li><?= $language ?></li>
			<?php	} ?>
		</ul>
	</div>
	<div>Assignment Specs: <?=stripslashes( $this->project['info']['assign_spec'] )?></div>
	<div>Project Approach: <?=stripslashes( $this->project['info']['project_approach'] )?></div>
</div>
</div>