<div class="contain-all">

<span class="aipd"></span>
<h1>Ts Projects</h1>

<div class="entryForm">

<h2>Create a new Account</h2>

<p><?php if(isset($this->alert)) { echo $this->alert; } ?></p>

<form action="/account/create" method="post">
	<label for="first_name">First Name</label>
	<input name="first_name"id="first_name" type="text" />
	<br />
	
	<label for="last_name">Last Name</label>
	<input name="last_name"id="last_name" type="text" />
	<br />
	
	<label for="email">Email</label>
	<input name="email"id="email" type="text" />
	<br />
	
	<label for="pass">Password</label>
	<input name="pass"id="pass" type="text" />
	<br />
	
	<label for="pass_verify">Password Verify</label>
	<input name="pass_verify"id="pass_verify" type="text" />
	<br />
	
	<label for="security_question">Security Question</label>
	<input name="security_question"id="security_question" type="text" />
	<br />
	
	<label for="security_answer">Security Answer</label>
	<input name="security_answer"id="security_answer" type="text" />
	
    <input type="submit" value="submit" id="submit"/>
</form>

</div>
</div>