<div id="user_dashboard" class="container contain-all">
<?php 
/**
* User's Dashboard of their own projects
* this will grab their newest 6 projects and display the for all the world to see
*/
?>



<?php if($this->user_id != "") { ?>
<a class="logout" href="/account/logout">logout</a>

<span class="user"><?= "User: " . $this->first_name . " " . $this->last_name; ?></span>
<?php 	} ?>
	

<span class="aipd"></span>
<h1>Ts Projects</h1>

<div class="entryForm">

<h2>This is the user dashboard for <?= $this->first_name . " " . $this->last_name; ?>.</h2>

<div class="options">
	<p>What would you like to do? </p>
	<a class="view" href="/">home</a>
	
	<a class="newProject" href="/project/new">add new project</a>
</div>		

<?php
		foreach ( $this->all_projects as $proj ) { ?>
	<div class="project">
		<div class="thumb">
			<img src="<?= (isset($proj['photo'])) ? "/uploads/{$proj['photo']['file_name']}" : "/images/default.jpg" ?>" />
		</div>
		<h3><a href="/project/view/id/<?= $proj['id'] ?>" ><?= $proj['title'] ?></a></h3>
		<h4><?= $proj['author'] ?></h4>
	</div>
<?php	} ?>
</div>
</div>