<div id="user_dashboard" class="container">
<?php 
/**
* User's Dashboard of their own projects
* this will grab their newest 6 projects and display the for all the world to see
*/
?>
<h1>This is the user dashboard for <?= $this->first_name . " " . $this->last_name; ?>.</h1>
<p>What would you like to do? </p>

<div class="options">
	<a href="/">Go Home</a>
	
	<a href="/project/new">Add A New Project</a>

	<a href="/account/logout">Logout</a>

	<span class="user"><?= "User: " . $this->first_name . " " . $this->last_name; ?></span>
</div>		

<?php
		foreach ( $this->all_projects as $proj ) { ?>
	<div class="project">
		<div class="thumb">
			<img src="<?= (isset($proj['photo'])) ? "/uploads/{$proj['photo']['file_name']}" : "/images/default.jpg" ?>" />
		</div>
		<h3><a href="/project/view/id/<?= $proj['id'] ?>" ><?= $proj['title'] ?></a></h3>
		<h4><?= $proj['author'] ?></h4>
	</div>
<?php	} ?>
</div>