<h1>Ts Projects</h1>

<div class="entryForm">
    <form action="/entry/create" method="post">
    <label>title:</label>
    <input type="text" class="text" />
    <br />
    <label>URL:</label>
    <input type="text" class="text" />
    <br />
    <label>project authors:</label>
    <input type="text" class="text" />
    <br /><br /><br />
    <label>class:</label>
    <input type="text" class="text" />
    <br />
<span class="tools">
    <label>tools:</label>
    <br />
    Photoshop
    <input type="checkbox"/>
    <br />
    Flash
    <input type="checkbox"/>
    <br />
    Illustrator
    <input type="checkbox"/>
    <br />
    Dreamweaver
    <input type="checkbox"/>
    <br />
    Coda
    <input type="checkbox"/>
    <br />
    Text Mate
    <input type="checkbox"/>
    <br />
    jQuery
    <input type="checkbox"/>
    <br />
</span>
<span class="language">
    <label>languages:</label>
    <br />
    HTML
    <input type="checkbox"/>
    <br />
    CSS
    <input type="checkbox"/>
    <br />
    XML
    <input type="checkbox"/>
    <br />
    Javascript
    <input type="checkbox"/>
    <br />
    PHP
    <input type="checkbox"/>
    <br />
    Actionscript
    <input type="checkbox"/>
</span>
<span class="clear"></span>
    <br />
    <label>date:</label>
    <input type="text" class="text"/>
    <br /><br /><br />
    <label>assignment specs:</label>
    <textarea name="assigmentSpec" rows="4" cols="60"></textarea>
    <br />
    <label>project approach:</label>
    <textarea name="projectApproach" rows="4" cols="60"></textarea>
    <br />
    <br />
    <input type="submit" value="submit" id="submit"/>
    </form>
</div>