<h1>Ts Projects</h1>

<div class="entryForm">
    <form action="/entry/create" method="post">
    <label>title:</label>
    <input type="text" class="text" name="title" id="title"/>
    <br />
    <label>URL:</label>
    <input type="text" class="text" name="url" id="url"/>
    <br />
    <label>project authors:</label>
    <input type="text" class="text" name="authors" id="authors" />
    <br /><br /><br />
    <label>class:</label>
    <input type="text" class="text" name="courses" id="courses" />
    <br />

<span class="contain-checkboxes">
<ul class="tools">
    <li><label>tools:</label></li>
    <li><input type="checkbox" name="photoshop" id="photoshop"/> Photoshop</li>
    <li><input type="checkbox" name="flash" id="flash"/> Flash</li>
    <li><input type="checkbox" name="illustrator" id="illustrator"/> Illustrator</li>
    <li><input type="checkbox" name="dreamweaver" id="dreamweaver"/> Dreamweaver</li>
    <li><input type="checkbox" name="fireworks" id="fireworks"/> Fireworks</li>
    <li><input type="checkbox" name="coda" id="coda"/> Coda</li>
    <li><input type="checkbox" name="textmate" id="textmate"/> TextMate</li>
    <li><input type="checkbox" name="jquery" id="jquery"/> jQuery</li>
    <li><input type="text" class="other-box" name="otherTools" id="otherTools" value="other" title="other"/></li>
</ul>

<ul class="languages">
    <li><label>languages:</label></li>
    <li><input type="checkbox" name="html" id="html"/> HTML</li>
    <li><input type="checkbox" name="css" id="css"/> CSS</li>
    <li><input type="checkbox" name="xml" id="xml"/> XML</li>
    <li><input type="checkbox" name="javascript" id="javascript"/> Javascript</li>
    <li><input type="checkbox" name="php" id="php"/> PHP</li>
    <li><input type="checkbox" name="actionscript" id="actionscript"/> Actionscript</li>
    <li><input type="text" value="other" name="otherLanguages" id="otherLanguages" class="other-box" title="other"/></li>
</ul>
</span>
    <br />
    <label>date:</label>
    <input type="text" class="text" name="date_complete" id="date_complete"/>
    <br /><br /><br />
    <label>assignment specs:</label>
    <textarea name="assigmentSpec" rows="4" cols="60" name="assign_spec" id="assign_spec"></textarea>
    <br />
    <br />
    <label>project approach:</label>
    <textarea name="projectApproach" rows="4" cols="60" name="project_approach" id="project_approach"></textarea>
    <br />
    <br />
    <input type="submit" value="submit" id="submit"/>
    </form>
</div>