<h1>Ts Projects</h1>

<div class="entryForm">
    <form action="/entry/create" method="post">
    <label>title:</label>
    <input type="text" class="text" name="title" id="title"/>
    <br />
    <label>URL:</label>
    <input type="text" class="text" name="url" id="url"/>
    <br />
    <label>class:</label>
    <input type="text" class="text" name="courses" id="courses" />
    <br />

<span class="contain-checkboxes">
<ul class="tools">
    <li><label>tools:</label></li>
    <li><input type="checkbox" name="photoshop" id="photoshop"/> Photoshop</li>
    <li><input type="checkbox" name="flash" id="flash"/> Flash</li>
    <li><input type="checkbox" name="illustrator" id="illustrator"/> Illustrator</li>
    <li><input type="checkbox" name="dreamweaver" id="dreamweaver"/> Dreamweaver</li>
    <li><input type="checkbox" name="fireworks" id="fireworks"/> Fireworks</li>
    <li><input type="checkbox" name="coda" id="coda"/> Coda</li>
    <li><input type="checkbox" name="textmate" id="textmate"/> TextMate</li>
    <li><input type="checkbox" name="jquery" id="jquery"/> jQuery</li>
    <li><input type="text" class="other-box" name="otherTools" id="otherTools" value="other" title="other"/></li>
</ul>

<ul class="languages">
    <li><label>languages:</label></li>
    <li><input type="checkbox" name="html" id="html"/> HTML</li>
    <li><input type="checkbox" name="css" id="css"/> CSS</li>
    <li><input type="checkbox" name="xml" id="xml"/> XML</li>
    <li><input type="checkbox" name="javascript" id="javascript"/> Javascript</li>
    <li><input type="checkbox" name="php" id="php"/> PHP</li>
    <li><input type="checkbox" name="actionscript" id="actionscript"/> Actionscript</li>
    <li><input type="text" value="other" name="otherLanguages" id="otherLanguages" class="other-box" title="other"/></li>
</ul>
</span>
    <br />
    <label>date:</label>
		<select name="month">
			<option value="default_month">Month</option>
			<option value="january">January</option>
			<option value="february">February</option>
			<option value="march">March</option>
			<option value="april">April</option>
			<option value="may">May</option>
			<option value="june">June</option>
			<option value="july">July</option>
			<option value="august">August</option>
			<option value="september">September</option>
			<option value="october">October</option>
			<option value="november">November</option>
			<option value="decemper">December</option>
		</select>
		
		<select name="day">
			<option value="default_day">Day</option>
			<?php for($i = 1; $i <= 31; $i++)
				print '<option value="day">' . $i . '</option>'
			 ?>
		</select>
		
		<select name="year">
			<option value="default_year">Year</option>
			<?php for($k = 2000; $k <= 2030; $k++) 
				print '<option value="year">' . $k . '</option>'
			 ?>
		</select>
    <br /><br /><br />
    <label>assignment specs:</label>
    <textarea rows="4" cols="60" name="assign_spec" id="assign_spec"></textarea>
    <br />
    <br />
    <label>project approach:</label>
    <textarea rows="4" cols="60" name="project_approach" id="project_approach"></textarea>
    <br />
    <br />
    <input type="submit" value="submit" id="submit"/>
    </form>
</div>