<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Ts Projects</title>
<style type="text/css">
* {
margin:0 auto;
padding:0;
}

.clear{
clear:both;
}

body{
background: #c9c9c9 url(images/bg_gradient-prime.png) no-repeat;
color:#434343;
font-family:Arial, Helvetica, sans-serif;
font-size:14px;
}

h1{
color:#434343;
font-family:Arial, Helvetica, sans-serif;
font-size:36px;
font-weight:400;
letter-spacing:-2px;
margin:15px;
text-align:center;
}

label{
text-align:right;
}

.text{
display:block;
height:32px;
width:488px;
}


.entryForm{
background:#FFF;
display:block;
height:auto;
padding:25px;
width:780px;


-webkit-border-radius: 18px;  
-moz-border-radius: 18px;  
-khtml-border-radius: 18px;  
border-radius: 18px; 
}

/*.tools, .language{
float:left;
}*/

#submit{
border:none;
background: transparent url(images/bg_butn-submit.png) no-repeat;
cursor:pointer;
display:block;
height:35px;
width:82px;
}

</style>
</head>

<body>
	<?= $this->layout()->content ?>
</body>
</html>